---
title: "Creating Pakages in R"
author: "Patrick Neary"
date: "September 24, 2015"
output: slidy_presentation
---

## Overview

This document details how to create a package to upload to github.  The inspiration for this document is from the following hilarypark link: <http://hilaryparker.com/2014/04/29/writing-an-r-package-from-scratch/>

There is another blog that discusses how to set up Git to receive this package: 
<http://www.r-bloggers.com/creating-your-personal-portable-r-code-library-with-github/>


-----

## Steps for creating R Packages

1. Preliminary packages to install
2. Create a directory for the R Package
3. Add function/code
4. Add documentation
5. Process Documentation
6. Run Install command
7. Make GitHub repo
8. Download and use repo in future projects

-----

## 1 - Preliminary packages to install

Several packages are necessary in order for packaging code.  The are:

1. devtools
2. roxygen2

These two packages are installed in the following code:

```

install.packages("Rcpp")
install.packages("stringi")
install.packages("devtools")
library("devtools")
devtools::install_github("klutometis/roxygen")
library(roxygen2)


```


## 2 - Create a directory for the R Package

The following code creates a directory in the users /AppData/Roaming/R for the package to go in.

```
  # path.expand with the tilde gives path to the current users document directory
  basepath = dirname(path.expand("~"))
  # create a path string for an R package to go into
  rPackageDir = sprintf("%s/AppData/Roaming/R/Packages", basepath)
  # Create the actual path
  dir.create(rPackageDir, TRUE, TRUE, "0777")
  # Set working directory to the path just created
  setwd(rPackageDir)
  # Create folder for new Package called multiplot.  
  # This function creates the directory structure necessary for a Package
  devtools::create("multiplot")
```

-----

## 3 - Add function and code

Create a .r script file that will contain the desired function.  These functions can be either grouped one per file or multiple functions can exist in the same file. This function should go in the 'R' subdirectory in the folder created in 1.

I found a useful file on the Internet called multiplot.r.  It allows for easy viewing plots in the same screen.  This code is available on github here: <https://github.com/trineary/practicum>

-----

## 4 - Add documentation

Each function will need a header before the function in the following format:

```
 
#' A Cat Function
#'
#' This function allows you to express your love of cats.
#' @param love Do you love cats? Defaults to TRUE.
#' @keywords cats
#' @export
#' @examples
#' cat_function()
 
cat_function <- function(love=TRUE){
    if(love==TRUE){
 ....
    }
}

```

## 5 - Process Documentation

To process the documentation, change working directory and then run the 'document' command.

```

  # Set the multiplot directory as working directory
  setwd('./multiplot')
  # Generate documentation
  document()

```

-----

## 6 - Run Install command


```
setwd('..')
install("multiplot")
```

-----

## 7 - Make GitHub repo

- Blog on setting up github to host package: <http://www.r-bloggers.com/creating-your-personal-portable-r-code-library-with-github/>


-----

## 8 - Download and use repo in future projects

The following command allows an automatic download and use of the repo:

```
install_github('trineary/multiplot','trineary')

```


Setting up GitHub to house the Package created above: <http://www.r-bloggers.com/creating-your-personal-portable-r-code-library-with-github/>

